### ISSUE TITLE
[Problem] Light Theme Only :(

### ISSUE THREAD

**Issue by Su4o** [bypassiwastaken/skiovox-helper#107]
On my chromebook, my default theme for all my kiosk apps is light theme mode. While going into my kiosk app, i tried to change it from light mode to dark mode, but when it goes to the "network not available" it goes to light mode..
any fix?

**Comment by 3kh0** [comment]
cry

**Comment by Gaboom63** [comment]
@Su4o When you have the menu open when you open skivox (alt  + Shift + S) That menu, you can click on the arrow next to the brightness slider on the right and then change it to dark mode.

**Comment by Su4o** [comment]
> cry

![sad-meme](https://github.com/bypassiwastaken/skiovox-helper/assets/127699325/6162f6db-68a9-4454-8103-d6afc2a2695c)

**Comment by Su4o** [comment]
> @Su4o When you have the menu open when you open skivox (alt + Shift + S) That menu, you can click on the arrow next to the brightness slider on the right and then change it to dark mode.

tried, but then when launched, turns into light mode.

**Comment by brobcoolguy** [comment]
just use a chrome extension from the web store

**Comment by Su4o** [comment]
> just use a chrome extension from the web store

Like what? themes sadly don't work.

**Comment by brobcoolguy** [comment]
> > just use a chrome extension from the web store
> 
> Like what? themes sadly don't work.

theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions

**Comment by Su4o** [comment]
> > > just use a chrome extension from the web store
> > 
> > 
> > Like what? themes sadly don't work.
> 
> theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions

oh, i meant the whole theme. like chromeos theme. I can't go into dark mode.

**Comment by brobcoolguy** [comment]
> > > > just use a chrome extension from the web store
> > > 
> > > 
> > > Like what? themes sadly don't work.
> > 
> > 
> > theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions
> 
> oh, i meant the whole theme. like chromeos theme. I can't go into dark mode.

oh, im not sure what you can do then. but if i recall correctly theres not much need for chrome-os dark mode when you're using skiovox, no? because last time i checked you cant see the taskbar and thats really the only thing dark mode changes i think.

**Comment by Su4o** [comment]
> > > > > just use a chrome extension from the web store
> > > > 
> > > > 
> > > > Like what? themes sadly don't work.
> > > 
> > > 
> > > theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions
> > 
> > 
> > oh, i meant the whole theme. like chromeos theme. I can't go into dark mode.
> 
> oh, im not sure what you can do then. but if i recall correctly theres not much need for chrome-os dark mode when you're using skiovox, no? because last time i checked you cant see the taskbar and thats really the only thing dark mode changes i think.

for file manager and so then websites dont automatically keep me on light mode.

**Comment by brobcoolguy** [comment]
> > > > > > just use a chrome extension from the web store
> > > > > 
> > > > > 
> > > > > Like what? themes sadly don't work.
> > > > 
> > > > 
> > > > theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions
> > > 
> > > 
> > > oh, i meant the whole theme. like chromeos theme. I can't go into dark mode.
> > 
> > 
> > oh, im not sure what you can do then. but if i recall correctly theres not much need for chrome-os dark mode when you're using skiovox, no? because last time i checked you cant see the taskbar and thats really the only thing dark mode changes i think.
> 
> for file manager and so then websites dont automatically keep me on light mode.

oh well im not sure what you can do but i noticed for me, skiovox automatically has dark mode for me when i go to settings and file manager. im using the 119 method so mabye you can try that?

**Comment by Su4o** [comment]
> > > > > > > just use a chrome extension from the web store
> > > > > > 
> > > > > > 
> > > > > > Like what? themes sadly don't work.
> > > > > 
> > > > > 
> > > > > theres dark mode extensions that arent themes, if chrome web store is unblocked just go there and search "dark mode" and you should find a ton of extentions
> > > > 
> > > > 
> > > > oh, i meant the whole theme. like chromeos theme. I can't go into dark mode.
> > > 
> > > 
> > > oh, im not sure what you can do then. but if i recall correctly theres not much need for chrome-os dark mode when you're using skiovox, no? because last time i checked you cant see the taskbar and thats really the only thing dark mode changes i think.
> > 
> > 
> > for file manager and so then websites dont automatically keep me on light mode.
> 
> oh well im not sure what you can do but i noticed for me, skiovox automatically has dark mode for me when i go to settings and file manager. im using the 119 method so mabye you can try that?

welp, i did. Seems like its just a problem for me. I'll be closing the issue.
