### ISSUE TITLE
can't sign in with google on some sites

### ISSUE THREAD

**Issue by nicolasog13** [bypassiwastaken/skiovox-helper#11]
since there are a lot of websites that open an external window to sign in with google, you can't access the window for the google sign in. is there any way that you guys could fix this?

**Comment by zek-c** [comment]
its becuase the popup cant popup

**Comment by bypassiwastaken** [comment]
@nicolasog13 i will be working on this over the next week or so.

**Comment by BadPingHere** [comment]
@nicolasog13 temp fix, try ctrl + clicking on the button. This should open said popup in a new tab, thereby allowing you to login.

**Comment by bypassiwastaken** [comment]
fixed this.
