### ISSUE TITLE
organization does not allow

### ISSUE THREAD

**Issue by Ender-Ghost-Craft** [bypassiwastaken/skiovox-helper#13]
add a way to bypass organization blocks

**Comment by 3kh0** [comment]
What is being blocked for you?

**Comment by DoxrGitHub** [comment]
same *.google.com is blocked for me and it looks like a policy block, it's not a wifi block

**Comment by Ender-Ghost-Craft** [comment]
github and google stuff
not google

**Comment by DoxrGitHub** [comment]
it's... different for every organization, for example, github isn't blocked for me

**Comment by Ender-Ghost-Craft** [comment]
its not wifi blocked, its organization blocked, but only on there for some reason, not normal chrome. maybe add a download that isn't github so my school can download it?

**Comment by bypassiwastaken** [comment]
dont talk about this here. this github is only for the extension.
also this is not possible
