### ISSUE TITLE
Skiovox extension blocked " Skiovox Helper (extension ID "peikdbpkagadaffgffppmcihhifllldc") is blocked by the administrator." I NEED HELP!!!

### ISSUE THREAD

**Issue by lostfor131** [bypassiwastaken/skiovox-helper#132]
so basically the extension switch is "off" and im trying to press delete and the same"
Skiovox Helper (extension ID "peikdbpkagadaffgffppmcihhifllldc") is blocked by the administrator." error shows up. im trying to install older versions but the same thing pops up. any help? also i need the page of the bluetooth thing because im trying to connect to smth but i cant find the page except for chrome://bluetooth-internals and it wont connect bc i keep getting an error. i need a fix. **_HELP PLEASEE_**

**Comment by lostfor131** [comment]
btw if you tell me to get the public key fix im gonna need a tut on what to do with it bc i just started using this site and idk what to do with the source code :C

**Comment by lostfor131** [comment]
nvm i got it

**Comment by im-aeo** [comment]
> btw if you tell me to get the public key fix im gonna need a tut on what to do with it bc i just started using this site and idk what to do with the source code :C

https://github.com/bypassiwastaken/skiovox-helper/issues/134#issuecomment-2142848875
