### ISSUE TITLE
Help my chromebook updated to 121 please help how do I downgrade it again I need help

### ISSUE THREAD

**Issue by FunnyDoggs** [bypassiwastaken/skiovox-helper#136]
I need to access my alt google account somebody help me.

**Comment by Legend7832** [comment]
U gonna have to wait till someone smart enough make another downgrade thingy :(

**Comment by FunnyDoggs** [comment]
Ok got it.

**Comment by Gaboom63** [comment]
> one smart enough make another downgrade thingy :(
 
Hey Man! You should fallow this guide: https://fog.gay/ Yes this isn't "Downgrading" but it unenrolls your device without admins seeing, also it will be down to version 107. You don't need to worry about the building image part you can download it here: https://dl.darkn.bio/E-Halcyon/Working/ So once you get to those linux commands you can skip over them. Good luck! Sorry that this isn't exactly what you are looking for but hope it helps!

**Comment by FunnyDoggs** [comment]
> > one smart enough make another downgrade thingy :(
> 
> Hey Man! You should fallow this guide: https://fog.gay/ Yes this isn't "Downgrading" but it unenrolls your device without admins seeing, also it will be down to version 107. You don't need to worry about the building image part you can download it here: https://dl.darkn.bio/E-Halcyon/Working/ So once you get to those linux commands you can skip over them. Good luck! Sorry that this isn't exactly what you are looking for but hope it helps!

@Fighterhen63 Thanks! I was able to find a friend still on 118 recently, and I was able to get 118 recov flashed and I was able to downgrade. I'll try the E-Halycon when I build up the confidence to do so.
