### ISSUE TITLE
2C method is trash and 2B doesn't work.

### ISSUE THREAD

**Issue by MythicalTrashcan** [bypassiwastaken/skiovox-helper#16]
I can't do 2A or 2B for some reason. 2C is the only method working. I can't actually test this on my computer anymore as it is on 105 and fakemurked, but I tested on my friends computer and it seems that 2C is the only one that works. And the skiovox helper extension is not working. If there is any way to getting 2A, that would be great as I could open multiple windows.

**Comment by 3kh0** [comment]
Go cry in a corner

**Comment by nicolasog13** [comment]
some chromebooks dont work and u gotta suck it up :/

**Comment by bypassiwastaken** [comment]
dont talk about this here
