### ISSUE TITLE
Can't connect to bluetooth device

### ISSUE THREAD

**Issue by YourEverydayGuy** [bypassiwastaken/skiovox-helper#18]
I need to connect to a bluetooth device, and I would normally open the taskbox, click on bluetooth, and pair with my device. This entire window is gone. I can't pair my bluetooth device. Is there a workaround? (I get that it isn't your problem but kiosk, but could you all make a button on the home page that requests to pair with bluetooth devices?)

**Comment by nicolasog13** [comment]
if you used stage 2B or 2C then you should be able to go to chrome://os-settings and connect to a bluetooth device from there.

**Comment by YourEverydayGuy** [comment]
Okay, ty!
