### ISSUE TITLE
Popup windows like chrome sign in tabs do not show

### ISSUE THREAD

**Issue by YourEverydayGuy** [bypassiwastaken/skiovox-helper#25]
I encountered this bug when I tried to log in to a website that said "grab my name from", with a  popup for a google sign-in. I already added 2 accounts, and I had to select an account to grab my name. The popup appeared for a little time, (maybe one screen tick) before it went away. Maybe always open links in the browser instead of creating a new window)

**Comment by bypassiwastaken** [comment]
fixed in latest version
