### ISSUE TITLE
Improve battery display message (QOL)

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [bypassiwastaken/skiovox-helper#35]
These changes:
![image](https://github.com/bypassiwastaken/skiovox-helper/assets/115495738/3e4b035b-c4fd-452a-b8cc-d264e336424b)
The battery message now says "Full" instead of "100%" and the charging message disappears when appropriate

**Comment by bypassiwastaken** [comment]
this is good. i might move the Math.min as its used 3? times

**Comment by bypassiwastaken** [comment]
but can you just make this a pull request
