### ISSUE TITLE
Add a link to the OS settings on new tab (QoL)

### ISSUE THREAD

**Issue by ironswordX-dev** [bypassiwastaken/skiovox-helper#37]
The name says it all :D 

If your wondering what the link to the os settings is, its chrome://os-settings , all it is is the settings app but in the browser

**Comment by 3kh0** [comment]
Duplicate of #5

**Comment by 3kh0** [comment]
![image](https://github.com/bypassiwastaken/skiovox-helper/assets/58097612/ac4baeb6-33aa-4c98-b493-88ed27c64794)

**Comment by ironswordX-dev** [comment]
oh srry, i didnt see that one

**Comment by ironswordX-dev** [comment]
oh srry, i didnt see that one
