### ISSUE TITLE
bluetooth, wifi, sound & brightness

### ISSUE THREAD

**Issue by Mazedotexe** [bypassiwastaken/skiovox-helper#40]
im not sure how limited extensions are, but if you can, please add sliders or something for sound and brightness, you can technically still use sound and brightness already but its hard to tell where your volume/brightness is at. this would be really cool.

and what would be even cooler would be bluetooth and wifi, your kinda just stuck with what you have for those

good luck if you actually do this ;)

**Comment by 3kh0** [comment]
I do think volume is possible, not so sure about anything else

**Comment by bypassiwastaken** [comment]
extension cannot control volume or brightness. you can edit bluetooth and wifi by opening device settings, thats a slide on skiovox.com

**Comment by nicolasog13** [comment]
2B or 2C only:

if you want to see your volume go to 
chrome://os-settings then to audio, then drag the slider

you cant check your brightness tho

**Comment by Mazedotexe** [comment]
ty bypassi, 2.4.0 has wifi/bluetooth on new tab page now :)

yeah i dont know what i was thinking with an extension controlling your os settings like brightness though it was late at night for me
