### ISSUE TITLE
proxy popup minimizes window (2B)

### ISSUE THREAD

**Issue by nicolasog13** [bypassiwastaken/skiovox-helper#41]
idk if this is fixable but if you are using any proxy on the chrome web store, then you get a popup that minimizes your chrome window after about 10-15 minutes. is there a way to prevent this popup or prevent the window from being force minimized? (this might also close the window, i dont know for sure)

![download](https://github.com/bypassiwastaken/skiovox-helper/assets/144080127/f711295e-eda9-476e-a904-d9124e3e95e2)

example of this in the image

**Comment by bypassiwastaken** [comment]
that's likely a school wifi thing. i havent heard of any other user having this issue

**Comment by nicolasog13** [comment]
ok, do you mind testing this to see if it happens to you? some of my friends i have showed this to also get this problem. it most likely is my schools proxy blocking it though

**Comment by simpansoftware** [comment]
i got a popup to about proxy. im using 2c
