### ISSUE TITLE
Secondary google accounts don't appear on youtube.

### ISSUE THREAD

**Issue by Landon-Kuehner** [bypassiwastaken/skiovox-helper#42]
When using the c variety of step 2; a secondary google account cannot be signed in on in youtube.

**Comment by bypassiwastaken** [comment]
can you send a video or picture of the issue?

**Comment by nicolasog13** [comment]
some troubleshooting options can include
- clearing cookies
- using the youtube business accounts feature
- or just deal with it, why do you even need two accs

**Comment by simpansoftware** [comment]
you could use this extension to get a screenshot: https://chromewebstore.google.com/detail/sk%C3%A4rminspelare-och-sk%C3%A4rmd/imopknpgdihifjkjpmjaagcagkefddnb if thats blocked then this is the extension id: imopknpgdihifjkjpmjaagcagkefddnb

**Comment by bypassiwastaken** [comment]
i will add screensoht functionality soon

**Comment by Epicminer256** [comment]
When you added your account, did you use the Add Account button in the new tab window, or did you do it from youtube.com directly?

**Comment by Person-Who-Exists** [comment]
> When you added your account, did you use the Add Account button in the new tab window, or did you do it from youtube.com directly?

I have tried it both ways, the secondary google account will not appear either way
