### ISSUE TITLE
Step 2b and 2c doesn't work.

### ISSUE THREAD

**Issue by GodHunter010** [bypassiwastaken/skiovox-helper#50]
I tried step 2 C and clicked escape twice and enter once within 4 seconds, but it did not do anything. So I moved on to the next step, 2 C, and opened Chromevox and clicked on one of the links in the resources. But they redirected me to the "Network Unavailable" screen. I, then, decided to try to click on each of the 3 links, but they all took me to the "Network Unavailable" screen. Please fix or create a new step.

**Comment by GodHunter010** [comment]
Just informing, I have kiosk apps.

**Comment by bypassiwastaken** [comment]
this isnt the place to ask for help. use discord.gg/unblock
