### ISSUE TITLE
Could I possibly be a collaborator of this project?

### ISSUE THREAD

**Issue by ironswordX-dev** [bypassiwastaken/skiovox-helper#54]
Hi, In recent weeks I have made improvements to this as a fork, which you can find at [the github repo](https://github.com/ironswordX-dev/Titanite), and I was wondering if I could be a collaborator of this project as I was able to update some things with it. Some of those things include:

- Updated battery display code (OC credits for it go to @Ant-Throw-Pology in #35 )
- Modernizing imports for the New Tab page so that there is no need for the clunky {} around what you want to import
- ...and a lot more

The latest release of it is still a WIP, but other than that I feel that i would be a great addition to the team

**Comment by 3kh0** [comment]
On your fork, sync the branch with upstream, then open a pull
