### ISSUE TITLE
idea suggestion

### ISSUE THREAD

**Issue by themirror289244** [bypassiwastaken/skiovox-helper#58]
would it be possible to open a completely isolated tab with the blocker extensions enabled (like the first tab you see when you execute skiovox)? We have securly, and my teacher is a power-hungry goblin and will call IT in for literally anything relating to my securly classroom being marked as "offline."

**Comment by zkayns** [comment]
open an image file from file manager and it should open a tab with the extensions enabled

**Comment by bypassiwastaken** [comment]
not unless you're using 2a. if you're using 2a there are quite a few ways to get that open. for example do the chromevox thing (2c) and that link will open in ur school profile
