### ISSUE TITLE
Navigator.appVersion is deprecated

### ISSUE THREAD

**Issue by Honkychunkymonkey** [bypassiwastaken/skiovox-helper#60]
(as shown in at [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion))

"Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time."

**Comment by bypassiwastaken** [comment]
dont care

**Comment by Honkychunkymonkey** [comment]
> dont care

😞
