### ISSUE TITLE
Not an Issue, but a feature

### ISSUE THREAD

**Issue by T3M1N4L** [bypassiwastaken/skiovox-helper#67]
It would be nice if we had shortcuts to apps, like on the chrome homepage. Also, I have noticed that chrome://flags options don't work, I turned on Chrome Refresh 2023 but it does not work. Also about skebstore, it seems to not be able to download chrome theme extensions. Also, is there a way to edit chrome policies on Skiovox browsers? It could help with unblocking google.com and allowing you to add a google account.

**Comment by bypassiwastaken** [comment]
not the place to talk about this. also no
