### ISSUE TITLE
Don't merge any PRs soon 

### ISSUE THREAD

**Issue by Honkychunkymonkey** [bypassiwastaken/skiovox-helper#70]
Hey, making a very large PR (basically refactor) soon in about 1-2 days, I've implemented a lot of stuff, (more than the current PRs lol), fixing bugs, adding features, QOL improvements, adding what would've been impossible, such as context menu (right click menu), Ctrl f support, and more to come soon :), so please don't merge any PRs soon :P

**Comment by 3kh0** [comment]
So steal the code we write, for yourself, I see

**Comment by Honkychunkymonkey** [comment]
> So steal the code we write, for yourself, I see

no? credit will be given to all of the writers of the original code, I just refactored it, a lot, a lot.

**Comment by Honkychunkymonkey** [comment]
> So steal the code we write, for yourself, I see

Also tf? It's public code, like I said I'm giving credit, and I'm making the extension faster, and just better in general :)

**Comment by 3kh0** [comment]
Ok I guess lol

**Comment by zek-c** [comment]
it is impossible, you cant make control f native only if you make a third party. same with context menu

**Comment by DanTCA1** [comment]
> it is impossible, you cant make control f native only if you make a third party. same with context menu

Pressing control f may not trigger it, but in the three dot context menu still includes a working find tool, there might be a way to trigger it in a different way

**Comment by zek-c** [comment]
no, there's not.

**Comment by Honkychunkymonkey** [comment]
> it is impossible, you cant make control f native only if you make a third party. same with context menu

yeah im making a third party one, it being an extension helps a lot

**Comment by Honkychunkymonkey** [comment]
> it is impossible, you cant make control f native only if you make a third party. same with context menu

and making a custom context menu is EXTREMELY easy, discord is a prime example of their custom Ctrl f and custom context menu

**Comment by Honkychunkymonkey** [comment]
> > > it is impossible, you cant make control f native only if you make a third party. same with context menu
> > 
> > and making a custom context menu is EXTREMELY easy, discord is a prime example of their custom Ctrl f and custom context menu
> 
> this

meh I kinda gave up on the "find" feature part, the native one has much better access to the whole page, and window.find doesn't seem very helpful at the moment. Also custom Ctrl f's kept opening as well as the custom skiovox one. Haven't found a way to fix that yet

**Comment by DanTCA1** [comment]
> > > > it is impossible, you cant make control f native only if you make a third party. same with context menu
> > > 
> > > 
> > > and making a custom context menu is EXTREMELY easy, discord is a prime example of their custom Ctrl f and custom context menu
> > 
> > 
> > this
> 
> meh I kinda gave up on the "find" feature part, the native one has much better access to the whole page, and window.find doesn't seem very helpful at the moment. Also custom Ctrl f's kept opening as well as the custom skiovox one. Haven't found a way to fix that yet

If you use the deprecated command that the rest of the commands (like ctrl+w for ex.), it doesn't send the command to the active webpage

**Comment by Honkychunkymonkey** [comment]
> hmm, so pointlessly doing a big pr for no reason I see

?

**Comment by Honkychunkymonkey** [comment]
closed due to drama

**Comment by zek-c** [comment]
buddy shut the hell up

**Comment by Honkychunkymonkey** [comment]
> buddy shut the hell up 

calm down, I closed this because of immature people like you.

**Comment by zek-c** [comment]
> > buddy shut the hell up
> 
> calm down, I closed this because of immature people like you.

i want you to end it

**Comment by Honkychunkymonkey** [comment]
> > > buddy shut the hell up
> > 
> > calm down, I closed this because of immature people like you.
> 
> i want you to end it

use a real programming language before you talk to me

**Comment by Honkychunkymonkey** [comment]
> > > > > it is impossible, you cant make control f native only if you make a third party. same with context menu
> > > > 
> > > > 
> > > > and making a custom context menu is EXTREMELY easy, discord is a prime example of their custom Ctrl f and custom context menu
> > > 
> > > 
> > > this
> > 
> > meh I kinda gave up on the "find" feature part, the native one has much better access to the whole page, and window.find doesn't seem very helpful at the moment. Also custom Ctrl f's kept opening as well as the custom skiovox one. Haven't found a way to fix that yet
> 
> Pulled from mdn web docs:
> > Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.
> 
> Pulled from StackOverflow:
> > You can't trigger Chrome's native find dialog
> 
> It generally seems like the find function is a lost cause.

I was experimenting with non window.find methods but nothing worked all the time.

**Comment by Honkychunkymonkey** [comment]
> > > > > buddy shut the hell up
> > > > 
> > > > calm down, I closed this because of immature people like you.
> > > 
> > > i want you to end it
> > 
> > use a real programming language before you talk to me 
> 
> i'm using javascript html and css and i'm learning C and this project YOU are doing is in javascript so what are you talking about lil bro

when I get home I'll publish my JavaScript runtime written in rust to my GitHub to if u want

**Comment by Honkychunkymonkey** [comment]
> > > > > buddy shut the hell up
> > > > 
> > > > calm down, I closed this because of immature people like you.
> > > 
> > > i want you to end it
> > 
> > use a real programming language before you talk to me 
> 
> i'm using javascript html and css and i'm learning C and this project YOU are doing is in javascript so what are you talking about lil bro

I also have written web frameworks from scratch in go and c++

**Comment by zek-c** [comment]
i don't give a fuck that you skidded some web server tutorial

**Comment by Honkychunkymonkey** [comment]
> i love when skids use big words <3

please explain how I am a "skid"?

**Comment by zek-c** [comment]
> > i don't give a fuck that you skidded some web server tutorial
> 
> do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down 

the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓

**Comment by blankuserrr** [comment]
> > > i don't give a fuck that you skidded some web server tutorial
> > 
> > do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down 
> 
> the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓

and what scripts am I using for my go framework? last time I checked im not using many scripts tbh

**Comment by blankuserrr** [comment]
> > > i don't give a fuck that you skidded some web server tutorial
> > 
> > do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down 
> 
> the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓

also, says the one who told me to "shut the hell up", and "end it"

**Comment by DanTCA1** [comment]
Guys just stop, this is the worst, petty, fight I have ever seen

**Comment by blankuserrr** [comment]
> Guys just stop, this is the worst, petty, fight I have ever seen

THANK YOU FOR STATING THE OBVIOUS 😭 I've just been thinking of blocking him

**Comment by zek-c** [comment]
> > > > i don't give a fuck that you skidded some web server tutorial
> > > 
> > > do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down 
> > 
> > the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓
> 
> and what scripts am I using for my go framework? last time I checked im not using many scripts tbh 

script kiddie means stealing code OR using scripts and thinking you're a coder/hacker

**Comment by blankuserrr** [comment]
> > > > > i don't give a fuck that you skidded some web server tutorial
> > > > 
> > > > do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down 
> > > 
> > > the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓
> > 
> > and what scripts am I using for my go framework? last time I checked im not using many scripts tbh 
> 
> script kiddie means stealing code OR using scripts and thinking you're a coder/hacker

please explain to me how I'm stealing code if I write it myself? is reading the docs stealing?

**Comment by zek-c** [comment]
> > > > > > i don't give a fuck that you skidded some web server tutorial
> > > > > 
> > > > > 
> > > > > do you know what from scratch means? also what? just because you're in tn doesn't mean you know the meaning of skid or skidding, and that proves you don't. Also there's a difference between servers and frameworks, you make servers with frameworks. frameworks take hundreds of lines of code, servers are 15 lines at most. stop being childish and calm down
> > > > 
> > > > 
> > > > the term "skid" does not come from Tn. it originates from script kiddie 😜  also you're getting pretty mad and defensive over me calling you a skid, proving you are one lol "fwamewoks and sevews awe difawent" 🤓
> > > 
> > > 
> > > and what scripts am I using for my go framework? last time I checked im not using many scripts tbh
> > 
> > 
> > script kiddie means stealing code OR using scripts and thinking you're a coder/hacker
> 
> please explain to me how I'm stealing code if I write it myself? is reading the docs stealing?

bro doesnt know the kodiak code 😭

**Comment by blankuserrr** [comment]
@bypassiwastaken can you please delete this if you can because I'm trying to not fight with immature children

**Comment by zek-c** [comment]
> @bypassiwastaken can you please delete this if you can because I'm trying to not fight with immature children

im gonna touch you

**Comment by blankuserrr** [comment]
> > @bypassiwastaken can you please delete this if you can because I'm trying to not fight with immature children
> 
> im gonna touch you

shhhh no one loves you
