### ISSUE TITLE
Bluetooth and Windows

### ISSUE THREAD

**Issue by GrassKeed** [bypassiwastaken/skiovox-helper#71]
i had this problem lately where i connect my earbuds but they disconnect sometimes, so i go to bluetooth pairing from the extension, but it only lets me pair new devices and not known devices so I have to sign into my school device, forget the earbuds, and reopen skiovox.
i also have this problem where i cant open multiple windows (i used the 2c step) but i saw this script part where it added a multi window feature for step 2b and step 2c people but idk how it works or if its just broken
![image](https://github.com/bypassiwastaken/skiovox-helper/assets/107058021/afb39a48-f1f6-4ff1-b340-73a2e739a8f5)

**Comment by iamsomeonedum** [comment]
srry for breaking ur eyes for light mode i never got the chance to change it lol cuz i barely use github

**Comment by Honkychunkymonkey** [comment]
chrome://os-settings :P

**Comment by GrassKeed** [comment]
is there any way to open multi windows?

**Comment by Honkychunkymonkey** [comment]
> is there any way to open multi windows?
>Multiple windows as in opening multiple instances of chrome/other apps or do you mean the multiple desktops? (I don't know how to explain them/what to call them sorry lol)

**Comment by zkayns** [comment]
> > is there any way to open multi windows?
> 
> Multiple windows as in opening multiple instances of chrome/other apps or do you mean the multiple desktops? (I don't know how to explain them/what to call them sorry lol)

pretty sure they're talking about new windows, not multiple desktops

**Comment by Honkychunkymonkey** [comment]
> > > is there any way to open multi windows?
> > 
> > Multiple windows as in opening multiple instances of chrome/other apps or do you mean the multiple desktops? (I don't know how to explain them/what to call them sorry lol)
> 
> pretty sure they're talking about new windows, not multiple desktops

I think with 2b/c you pretty much can't

**Comment by GrassKeed** [comment]
> # In short, that isn't what that file does.
> That file actually stops sites from opening pages in new windows, because Skiovox doesn't support it.
will it be supported in the future?

**Comment by bypassiwastaken** [comment]
i cannot fix this. the file you are talking about fixes google logins by making them open in the same window, due to the fact that doing otherwise isn't possible on 2b/2c.

also no i will not be adding an os-settings link to the homepage because that crashes 2a users
