### ISSUE TITLE
Not working sometimes.

### ISSUE THREAD

**Issue by wew7** [bypassiwastaken/skiovox-helper#72]
Msot of the time you use this it will go like :site could not be reached" and "Google.com took to long to respond" can you fix this?

**Comment by zkayns** [comment]
i don't think this is an issue with skiovox

**Comment by Honkychunkymonkey** [comment]
> i don't think this is an issue with skiovox

👍

**Comment by Honkychunkymonkey** [comment]
not an issue with skiovox, please close this
