### ISSUE TITLE
"the connection was reset" problem

### ISSUE THREAD

**Issue by username101010101** [bypassiwastaken/skiovox-helper#76]
most apps when trying to go in it says connection is reset

**Comment by DanTCA1** [comment]
This may be a firewall issue while in your school, if so you need to download a vpn from chrome web store

**Comment by username101010101** [comment]
> This may be a firewall issue while in your school, if so you need to download a vpn from chrome web store

already tried that

**Comment by Honkychunkymonkey** [comment]
it's not a problem with skiovox, please close this

**Comment by tuta-amb** [comment]
@bypassiwastaken @username101010101 close this please
