### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by simpansoftware** [bypassiwastaken/skiovox-helper#79]
Can you add a shortcut like CTRL+SHIFT+F to toggle fullscreen?

**Comment by blankuserrr** [comment]
why not use the shortcut button for fullscreen that's already on your keyboard?

**Comment by Su4o** [comment]
Well, here's a solution. 

Requirments: 

1. Using the 2B or 2C Method
yeah thats all. (people can do this method in 2A, but then you're going to lose the shortcut of opening a new window)
--------------------------------
Here's the steps!
--------------------------------

1.  Download [this extension](https://chromewebstore.google.com/detail/toggle-fullscreen/ddpejemcmlhbjppfdndmonifbiaindkl)

2. go to [chrome://extensions](chrome://extensions). On the sidebar, click "keyboard shortcuts"

3. Now, find "Toggle Fullscreen" 

4. Put "Activate the extension" to CTRL + F (F stands for fullscreen & anyways sadly, you can't use the find feature by CTRL + F, _you gotta do it manually_. )

5. Now scroll up to Skiovox Helper. Find the Ctrl+N Option. Now this might be weird, but trust me. Change the CTRL + N option to CTRL + SHIFT + F. 
--------------------------------

Now whenever you want to full screen, press CTRL + F. To go back, press CTRL + SHIFT + F

--------------------------------
Note: If your a 2A member, you lose the ability to open a new window if you've done this.
