### ISSUE TITLE
Add shortcut

### ISSUE THREAD

**Issue by localuser-isback** [bypassiwastaken/skiovox-helper#87]
Would be nice to add a shortcut for chrome://os-settings/ as it can do most of the things already added on shortcuts and more.

**Comment by 3kh0** [comment]
This can not work for a few people

**Comment by pictureofhotdogplus** [comment]
if you go to vscode.dev and import the extension folder, you can go to i think newtab/main.js and edit the links

**Comment by localuser-isback** [comment]
Alright thanks. i might just make a custom fork with some personal customizations then.
