### ISSUE TITLE
Add switching between windows (alt tab)

### ISSUE THREAD

**Issue by Blobby-Boi** [bypassiwastaken/skiovox-helper#93]
I know how you can do this just make it bring up the popup that says "share your screen" and then when you click on any of the windows it  sends you to them. You can just make it instantly stop sharing screen. Boom, alt tab is back.

**Comment by Epicminer256** [comment]
I think you can switch windows with Alt+Q. If this works you can rebind it if you want

**Comment by Epicminer256** [comment]
I don't have 2.a so idk
